# Generated by Django 5.0.3 on 2024-04-16 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='merchant_id',
        ),
    ]
