# Generated by Django 5.0.3 on 2024-05-31 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_transaction_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_uuid',
        ),
    ]
