# Generated by Django 5.0.3 on 2024-05-31 02:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_transaction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
