# Generated by Django 5.1.3 on 2024-12-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productvariation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
